version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/falling_balls"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/spells"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
